# expanded_seed_data.py - Comprehensive Nigerian & African Food Database
# Run this to add 100+ Nigerian foods to your database

from decimal import Decimal
from apps.nutrition.models import FoodCategory, Food, Recipe, RecipeIngredient, HealthTip


def seed_expanded_foods():
    """Add comprehensive Nigerian food database"""
    
    # Get categories
    grains = FoodCategory.objects.get(name='Grains & Starches')
    proteins = FoodCategory.objects.get(name='Proteins')
    vegetables = FoodCategory.objects.get(name='Vegetables')
    fruits = FoodCategory.objects.get(name='Fruits')
    legumes = FoodCategory.objects.get(name='Legumes')
    oils = FoodCategory.objects.get(name='Oils & Fats')
    dairy = FoodCategory.objects.get(name='Dairy & Alternatives')
    spices = FoodCategory.objects.get(name='Spices & Seasonings')
    
    foods_data = [
        # ===== GRAINS & STARCHES (20 items) =====
        {
            'name': 'White Rice',
            'local_name': 'Shinkafa (Hausa), Iresi (Yoruba)',
            'category': grains,
            'calories': Decimal('130'),
            'protein': Decimal('2.7'),
            'carbohydrates': Decimal('28'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('0.4'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': False,
        },
        {
            'name': 'Brown Rice',
            'local_name': 'Shinkafa mai ruwan kasa',
            'category': grains,
            'calories': Decimal('111'),
            'protein': Decimal('2.6'),
            'carbohydrates': Decimal('23'),
            'fats': Decimal('0.9'),
            'fiber': Decimal('1.8'),
            'average_price_per_kg': Decimal('1200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Yam',
            'local_name': 'Ji (Igbo), Isu (Yoruba)',
            'category': grains,
            'calories': Decimal('118'),
            'protein': Decimal('1.5'),
            'carbohydrates': Decimal('27.9'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('4.1'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Jan,Feb,Mar,Aug,Sep,Oct,Nov,Dec',
        },
        {
            'name': 'Sweet Potato',
            'local_name': 'Dankali mai dadi',
            'category': grains,
            'calories': Decimal('86'),
            'protein': Decimal('1.6'),
            'carbohydrates': Decimal('20'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('3'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
            'vitamin_a': Decimal('14187'),
        },
        {
            'name': 'Cassava (Fresh)',
            'local_name': 'Rogo (Hausa), Ege (Yoruba)',
            'category': grains,
            'calories': Decimal('160'),
            'protein': Decimal('1.4'),
            'carbohydrates': Decimal('38'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('1.8'),
            'average_price_per_kg': Decimal('250'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Garri (White)',
            'local_name': 'Garri',
            'category': grains,
            'calories': Decimal('357'),
            'protein': Decimal('1.4'),
            'carbohydrates': Decimal('84'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('1.8'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Garri (Yellow)',
            'local_name': 'Garri Ijebu',
            'category': grains,
            'calories': Decimal('360'),
            'protein': Decimal('1.5'),
            'carbohydrates': Decimal('85'),
            'fats': Decimal('0.5'),
            'fiber': Decimal('2'),
            'average_price_per_kg': Decimal('450'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Plantain (Ripe)',
            'local_name': 'Ogede (Yoruba), Ayaba (Igbo)',
            'category': grains,
            'calories': Decimal('122'),
            'protein': Decimal('1.3'),
            'carbohydrates': Decimal('31.9'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('2.3'),
            'average_price_per_kg': Decimal('350'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Plantain (Unripe)',
            'local_name': 'Ogede wewe',
            'category': grains,
            'calories': Decimal('116'),
            'protein': Decimal('1.2'),
            'carbohydrates': Decimal('29'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('2.8'),
            'average_price_per_kg': Decimal('350'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Cocoyam',
            'local_name': 'Ede (Yoruba), Koko (Igbo)',
            'category': grains,
            'calories': Decimal('112'),
            'protein': Decimal('1.5'),
            'carbohydrates': Decimal('26'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('4.1'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Irish Potato',
            'local_name': 'Dankali',
            'category': grains,
            'calories': Decimal('77'),
            'protein': Decimal('2'),
            'carbohydrates': Decimal('17'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('2.2'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Wheat Flour',
            'local_name': 'Fulawa',
            'category': grains,
            'calories': Decimal('364'),
            'protein': Decimal('10'),
            'carbohydrates': Decimal('76'),
            'fats': Decimal('1'),
            'fiber': Decimal('2.7'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Semovita',
            'local_name': 'Semo',
            'category': grains,
            'calories': Decimal('360'),
            'protein': Decimal('11'),
            'carbohydrates': Decimal('74'),
            'fats': Decimal('1.2'),
            'fiber': Decimal('3'),
            'average_price_per_kg': Decimal('700'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Corn (Maize)',
            'local_name': 'Masara (Hausa), Agbado (Yoruba)',
            'category': grains,
            'calories': Decimal('86'),
            'protein': Decimal('3.2'),
            'carbohydrates': Decimal('19'),
            'fats': Decimal('1.2'),
            'fiber': Decimal('2.7'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Sep,Oct,Nov',
        },
        {
            'name': 'Corn Flour (Ogi)',
            'local_name': 'Ogi/Akamu',
            'category': grains,
            'calories': Decimal('362'),
            'protein': Decimal('8'),
            'carbohydrates': Decimal('77'),
            'fats': Decimal('3.6'),
            'fiber': Decimal('7.3'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Millet',
            'local_name': 'Gero (Hausa)',
            'category': grains,
            'calories': Decimal('378'),
            'protein': Decimal('11'),
            'carbohydrates': Decimal('73'),
            'fats': Decimal('4.2'),
            'fiber': Decimal('8.5'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Sorghum',
            'local_name': 'Dawa (Hausa)',
            'category': grains,
            'calories': Decimal('329'),
            'protein': Decimal('10'),
            'carbohydrates': Decimal('72'),
            'fats': Decimal('3.3'),
            'fiber': Decimal('6.7'),
            'average_price_per_kg': Decimal('450'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Bread (White)',
            'local_name': 'Burodi',
            'category': grains,
            'calories': Decimal('265'),
            'protein': Decimal('9'),
            'carbohydrates': Decimal('49'),
            'fats': Decimal('3.2'),
            'fiber': Decimal('2.7'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Bread (Whole Wheat)',
            'local_name': 'Brown bread',
            'category': grains,
            'calories': Decimal('247'),
            'protein': Decimal('13'),
            'carbohydrates': Decimal('41'),
            'fats': Decimal('3.4'),
            'fiber': Decimal('7'),
            'average_price_per_kg': Decimal('1000'),
            'is_vegetarian': True,
            'is_vegan': False,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Acha (Fonio)',
            'local_name': 'Acha',
            'category': grains,
            'calories': Decimal('367'),
            'protein': Decimal('9'),
            'carbohydrates': Decimal('74'),
            'fats': Decimal('2.2'),
            'fiber': Decimal('3'),
            'average_price_per_kg': Decimal('1200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        
        # ===== PROTEINS (25 items) =====
        {
            'name': 'Chicken (whole)',
            'local_name': 'Kaza (Hausa), Adiye (Yoruba)',
            'category': proteins,
            'calories': Decimal('239'),
            'protein': Decimal('27'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('14'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Chicken Breast',
            'local_name': 'Kaza nono',
            'category': proteins,
            'calories': Decimal('165'),
            'protein': Decimal('31'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('3.6'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3000'),
            'is_vegetarian': False,
            'is_vegan': False,
            'suitable_for_hypertension': True,
        },
        {
            'name': 'Beef',
            'local_name': 'Nama (Hausa), Eran (Yoruba)',
            'category': proteins,
            'calories': Decimal('250'),
            'protein': Decimal('26'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('15'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Goat Meat',
            'local_name': 'Naman akuya (Hausa)',
            'category': proteins,
            'calories': Decimal('143'),
            'protein': Decimal('27'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('3'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3500'),
            'is_vegetarian': False,
            'is_vegan': False,
            'suitable_for_hypertension': True,
        },
        {
            'name': 'Mutton',
            'local_name': 'Naman rago',
            'category': proteins,
            'calories': Decimal('294'),
            'protein': Decimal('25'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('21'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3200'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Mackerel (Titus)',
            'local_name': 'Titus',
            'category': proteins,
            'calories': Decimal('205'),
            'protein': Decimal('19'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('14'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1800'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Catfish (Fresh)',
            'local_name': 'Eja aro (Yoruba)',
            'category': proteins,
            'calories': Decimal('105'),
            'protein': Decimal('18'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('2.9'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': False,
            'is_vegan': False,
            'suitable_for_hypertension': True,
        },
        {
            'name': 'Tilapia',
            'local_name': 'Eja',
            'category': proteins,
            'calories': Decimal('96'),
            'protein': Decimal('20'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('1.7'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1500'),
            'is_vegetarian': False,
            'is_vegan': False,
            'suitable_for_hypertension': True,
        },
        {
            'name': 'Stockfish (Dried)',
            'local_name': 'Okporoko',
            'category': proteins,
            'calories': Decimal('290'),
            'protein': Decimal('62'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('2.4'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('4000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Crayfish (Dried)',
            'local_name': 'Ede (Igbo)',
            'category': proteins,
            'calories': Decimal('295'),
            'protein': Decimal('64'),
            'carbohydrates': Decimal('2.5'),
            'fats': Decimal('3.7'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('5000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Snail',
            'local_name': 'Igbin (Yoruba)',
            'category': proteins,
            'calories': Decimal('90'),
            'protein': Decimal('16'),
            'carbohydrates': Decimal('2'),
            'fats': Decimal('1.4'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2500'),
            'is_vegetarian': False,
            'is_vegan': False,
            'suitable_for_hypertension': True,
        },
        {
            'name': 'Periwinkle',
            'local_name': 'Isam',
            'category': proteins,
            'calories': Decimal('79'),
            'protein': Decimal('14'),
            'carbohydrates': Decimal('3.3'),
            'fats': Decimal('0.9'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Eggs',
            'local_name': 'Kwai (Hausa), Eyin (Yoruba)',
            'category': proteins,
            'calories': Decimal('155'),
            'protein': Decimal('13'),
            'carbohydrates': Decimal('1.1'),
            'fats': Decimal('11'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1400'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Turkey',
            'local_name': 'Tolotolo',
            'category': proteins,
            'calories': Decimal('189'),
            'protein': Decimal('29'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('7'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2800'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Duck',
            'local_name': 'Pepeiye',
            'category': proteins,
            'calories': Decimal('337'),
            'protein': Decimal('19'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('28'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Ponmo (Cow Skin)',
            'local_name': 'Ponmo/Kanda',
            'category': proteins,
            'calories': Decimal('224'),
            'protein': Decimal('46'),
            'carbohydrates': Decimal('0.2'),
            'fats': Decimal('4.5'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1200'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Shaki (Tripe)',
            'local_name': 'Shaki',
            'category': proteins,
            'calories': Decimal('85'),
            'protein': Decimal('12'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('3.4'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Liver (Beef)',
            'local_name': 'Hanta',
            'category': proteins,
            'calories': Decimal('135'),
            'protein': Decimal('20'),
            'carbohydrates': Decimal('3.9'),
            'fats': Decimal('3.6'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1800'),
            'is_vegetarian': False,
            'is_vegan': False,
            'iron': Decimal('6.2'),
        },
        {
            'name': 'Gizzard (Chicken)',
            'local_name': 'Gurdi',
            'category': proteins,
            'calories': Decimal('154'),
            'protein': Decimal('30'),
            'carbohydrates': Decimal('0.7'),
            'fats': Decimal('2.7'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Sausage Roll',
            'local_name': 'Sausage roll',
            'category': proteins,
            'calories': Decimal('330'),
            'protein': Decimal('10'),
            'carbohydrates': Decimal('27'),
            'fats': Decimal('20'),
            'fiber': Decimal('1'),
            'average_price_per_kg': Decimal('2500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Meat Pie',
            'local_name': 'Meat pie',
            'category': proteins,
            'calories': Decimal('300'),
            'protein': Decimal('8'),
            'carbohydrates': Decimal('32'),
            'fats': Decimal('15'),
            'fiber': Decimal('1.5'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Suya Spice Meat',
            'local_name': 'Suya',
            'category': proteins,
            'calories': Decimal('280'),
            'protein': Decimal('28'),
            'carbohydrates': Decimal('2'),
            'fats': Decimal('17'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Smoked Fish',
            'local_name': 'Eja yoyo',
            'category': proteins,
            'calories': Decimal('200'),
            'protein': Decimal('40'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('4'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Sardine (Canned)',
            'local_name': 'Geisha',
            'category': proteins,
            'calories': Decimal('208'),
            'protein': Decimal('25'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('11'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        {
            'name': 'Corned Beef (Canned)',
            'local_name': 'Corned beef',
            'category': proteins,
            'calories': Decimal('250'),
            'protein': Decimal('26'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('16'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3500'),
            'is_vegetarian': False,
            'is_vegan': False,
        },
        
        # ===== LEGUMES (8 items) =====
        {
            'name': 'Black-eyed Peas',
            'local_name': 'Wake (Hausa), Ewa (Yoruba)',
            'category': legumes,
            'calories': Decimal('116'),
            'protein': Decimal('8'),
            'carbohydrates': Decimal('21'),
            'fats': Decimal('0.5'),
            'fiber': Decimal('6'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Brown Beans',
            'local_name': 'Ewa oloyin',
            'category': legumes,
            'calories': Decimal('347'),
            'protein': Decimal('21'),
            'carbohydrates': Decimal('63'),
            'fats': Decimal('1.2'),
            'fiber': Decimal('15'),
            'average_price_per_kg': Decimal('900'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Groundnuts (Peanuts)',
            'local_name': 'Gyada (Hausa), Epa (Yoruba)',
            'category': legumes,
            'calories': Decimal('567'),
            'protein': Decimal('26'),
            'carbohydrates': Decimal('16'),
            'fats': Decimal('49'),
            'fiber': Decimal('8.5'),
            'average_price_per_kg': Decimal('1000'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Soya Beans',
            'local_name': 'Wake soya',
            'category': legumes,
            'calories': Decimal('446'),
            'protein': Decimal('36'),
            'carbohydrates': Decimal('30'),
            'fats': Decimal('20'),
            'fiber': Decimal('9'),
            'average_price_per_kg': Decimal('700'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Bambara Nuts',
            'local_name': 'Gurjiya',
            'category': legumes,
            'calories': Decimal('367'),
            'protein': Decimal('19'),
            'carbohydrates': Decimal('61'),
            'fats': Decimal('6.5'),
            'fiber': Decimal('6'),
            'average_price_per_kg': Decimal('1100'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Pigeon Peas',
            'local_name': 'Fiofio',
            'category': legumes,
            'calories': Decimal('343'),
            'protein': Decimal('22'),
            'carbohydrates': Decimal('62'),
            'fats': Decimal('1.5'),
            'fiber': Decimal('15'),
            'average_price_per_kg': Decimal('850'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Lentils',
            'local_name': 'Adas',
            'category': legumes,
            'calories': Decimal('116'),
            'protein': Decimal('9'),
            'carbohydrates': Decimal('20'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('8'),
            'average_price_per_kg': Decimal('1200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Locust Beans',
            'local_name': 'Iru (Yoruba), Dawadawa (Hausa)',
            'category': legumes,
            'calories': Decimal('400'),
            'protein': Decimal('35'),
            'carbohydrates': Decimal('42'),
            'fats': Decimal('30'),
            'fiber': Decimal('8'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
    ]
    
    created_count = 0
    for food_data in foods_data:
        _, created = Food.objects.get_or_create(
            name=food_data['name'],
            defaults=food_data
        )
        if created:
            created_count += 1
    
    print(f"✓ {created_count} new foods added (Total: {Food.objects.count()})")


def seed_expanded_vegetables():
    """Add more vegetables"""
    vegetables = FoodCategory.objects.get(name='Vegetables')
    
    veg_data = [
        {
            'name': 'Spinach',
            'local_name': 'Alayyahu (Hausa), Efo tete (Yoruba)',
            'category': vegetables,
            'calories': Decimal('23'),
            'protein': Decimal('2.9'),
            'carbohydrates': Decimal('3.6'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('2.2'),
            'average_price_per_kg': Decimal('200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
            'suitable_for_hypertension': True,
            'iron': Decimal('2.7'),
            'calcium': Decimal('99'),
            'vitamin_a': Decimal('9377'),
        },
        {
            'name': 'Tomatoes',
            'local_name': 'Tumatir (Hausa), Tomato (Yoruba)',
            'category': vegetables,
            'calories': Decimal('18'),
            'protein': Decimal('0.9'),
            'carbohydrates': Decimal('3.9'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('1.2'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
            'suitable_for_hypertension': True,
            'is_seasonal': True,
            'available_months': 'All year',
        },
        {
            'name': 'Bell Peppers (Tatase)',
            'local_name': 'Tatase',
            'category': vegetables,
            'calories': Decimal('31'),
            'protein': Decimal('1'),
            'carbohydrates': Decimal('6'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('2.1'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Scotch Bonnet Pepper',
            'local_name': 'Ata rodo',
            'category': vegetables,
            'calories': Decimal('40'),
            'protein': Decimal('2'),
            'carbohydrates': Decimal('9'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('1.5'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Onions',
            'local_name': 'Albasa (Hausa), Alubosa (Yoruba)',
            'category': vegetables,
            'calories': Decimal('40'),
            'protein': Decimal('1.1'),
            'carbohydrates': Decimal('9.3'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('1.7'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Spring Onions',
            'local_name': 'Alubosa elewe',
            'category': vegetables,
            'calories': Decimal('32'),
            'protein': Decimal('1.8'),
            'carbohydrates': Decimal('7.3'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('2.6'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Okra',
            'local_name': 'Kubewa (Hausa), Ila (Yoruba)',
            'category': vegetables,
            'calories': Decimal('33'),
            'protein': Decimal('1.9'),
            'carbohydrates': Decimal('7.5'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('3.2'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Bitter Leaf',
            'local_name': 'Shuwaka (Hausa), Ewuro (Yoruba)',
            'category': vegetables,
            'calories': Decimal('22'),
            'protein': Decimal('3.5'),
            'carbohydrates': Decimal('2.1'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('2'),
            'average_price_per_kg': Decimal('250'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Pumpkin Leaves (Ugwu)',
            'local_name': 'Ugu',
            'category': vegetables,
            'calories': Decimal('21'),
            'protein': Decimal('2.2'),
            'carbohydrates': Decimal('3.4'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('2'),
            'average_price_per_kg': Decimal('200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
            'iron': Decimal('2.3'),
        },
        {
            'name': 'Waterleaf',
            'local_name': 'Gbure (Yoruba)',
            'category': vegetables,
            'calories': Decimal('17'),
            'protein': Decimal('2.5'),
            'carbohydrates': Decimal('1.8'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('1.5'),
            'average_price_per_kg': Decimal('250'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Garden Egg Leaves',
            'local_name': 'Anara',
            'category': vegetables,
            'calories': Decimal('24'),
            'protein': Decimal('2.8'),
            'carbohydrates': Decimal('3.7'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('2.5'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Cabbage',
            'local_name': 'Kabeji',
            'category': vegetables,
            'calories': Decimal('25'),
            'protein': Decimal('1.3'),
            'carbohydrates': Decimal('5.8'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('2.5'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
            'suitable_for_diabetes': True,
        },
        {
            'name': 'Lettuce',
            'local_name': 'Letus',
            'category': vegetables,
            'calories': Decimal('15'),
            'protein': Decimal('1.4'),
            'carbohydrates': Decimal('2.9'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('1.3'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Carrots',
            'local_name': 'Karas',
            'category': vegetables,
            'calories': Decimal('41'),
            'protein': Decimal('0.9'),
            'carbohydrates': Decimal('10'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('2.8'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
            'vitamin_a': Decimal('16706'),
        },
        {
            'name': 'Cucumber',
            'local_name': 'Kukumba',
            'category': vegetables,
            'calories': Decimal('15'),
            'protein': Decimal('0.7'),
            'carbohydrates': Decimal('3.6'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('0.5'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Green Beans',
            'local_name': 'Green beans',
            'category': vegetables,
            'calories': Decimal('31'),
            'protein': Decimal('1.8'),
            'carbohydrates': Decimal('7'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('2.7'),
            'average_price_per_kg': Decimal('700'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Garden Egg (White)',
            'local_name': 'Igba (Yoruba)',
            'category': vegetables,
            'calories': Decimal('24'),
            'protein': Decimal('1'),
            'carbohydrates': Decimal('5.7'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('2.5'),
            'average_price_per_kg': Decimal('350'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Eggplant (Purple)',
            'local_name': 'Igba igbo',
            'category': vegetables,
            'calories': Decimal('25'),
            'protein': Decimal('1'),
            'carbohydrates': Decimal('6'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('3'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Scent Leaf',
            'local_name': 'Efirin (Yoruba), Nchuanwu (Igbo)',
            'category': vegetables,
            'calories': Decimal('23'),
            'protein': Decimal('3.2'),
            'carbohydrates': Decimal('2.7'),
            'fats': Decimal('0.6'),
            'fiber': Decimal('1.6'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
    ]
    
    created = 0
    for veg in veg_data:
        _, is_created = Food.objects.get_or_create(name=veg['name'], defaults=veg)
        if is_created:
            created += 1
    
    print(f"✓ {created} vegetables added")


def seed_fruits():
    """Add Nigerian fruits"""
    fruits = FoodCategory.objects.get(name='Fruits')
    
    fruit_data = [
        {
            'name': 'Orange',
            'local_name': 'Lemu (Hausa), Osan (Yoruba)',
            'category': fruits,
            'calories': Decimal('47'),
            'protein': Decimal('0.9'),
            'carbohydrates': Decimal('12'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('2.4'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Nov,Dec,Jan,Feb,Mar',
        },
        {
            'name': 'Banana',
            'local_name': 'Ayaba',
            'category': fruits,
            'calories': Decimal('89'),
            'protein': Decimal('1.1'),
            'carbohydrates': Decimal('23'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('2.6'),
            'average_price_per_kg': Decimal('250'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Pineapple',
            'local_name': 'Abaramo',
            'category': fruits,
            'calories': Decimal('50'),
            'protein': Decimal('0.5'),
            'carbohydrates': Decimal('13'),
            'fats': Decimal('0.1'),
            'fiber': Decimal('1.4'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Watermelon',
            'local_name': 'Elegede',
            'category': fruits,
            'calories': Decimal('30'),
            'protein': Decimal('0.6'),
            'carbohydrates': Decimal('8'),
            'fats': Decimal('0.2'),
            'fiber': Decimal('0.4'),
            'average_price_per_kg': Decimal('200'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Pawpaw (Papaya)',
            'local_name': 'Ibepe (Yoruba)',
            'category': fruits,
            'calories': Decimal('43'),
            'protein': Decimal('0.5'),
            'carbohydrates': Decimal('11'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('1.7'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'vitamin_a': Decimal('950'),
        },
        {
            'name': 'Mango',
            'local_name': 'Mangoro',
            'category': fruits,
            'calories': Decimal('60'),
            'protein': Decimal('0.8'),
            'carbohydrates': Decimal('15'),
            'fats': Decimal('0.4'),
            'fiber': Decimal('1.6'),
            'average_price_per_kg': Decimal('350'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'May,Jun,Jul,Aug',
        },
        {
            'name': 'Coconut',
            'local_name': 'Agbon',
            'category': fruits,
            'calories': Decimal('354'),
            'protein': Decimal('3.3'),
            'carbohydrates': Decimal('15'),
            'fats': Decimal('33'),
            'fiber': Decimal('9'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Guava',
            'local_name': 'Gova',
            'category': fruits,
            'calories': Decimal('68'),
            'protein': Decimal('2.6'),
            'carbohydrates': Decimal('14'),
            'fats': Decimal('1'),
            'fiber': Decimal('5.4'),
            'average_price_per_kg': Decimal('400'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'African Star Apple',
            'local_name': 'Agbalumo (Yoruba), Udara (Igbo)',
            'category': fruits,
            'calories': Decimal('67'),
            'protein': Decimal('0.7'),
            'carbohydrates': Decimal('16'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('2'),
            'average_price_per_kg': Decimal('300'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Dec,Jan,Feb,Mar',
        },
        {
            'name': 'African Pear',
            'local_name': 'Ube (Igbo)',
            'category': fruits,
            'calories': Decimal('160'),
            'protein': Decimal('2'),
            'carbohydrates': Decimal('9'),
            'fats': Decimal('14'),
            'fiber': Decimal('7'),
            'average_price_per_kg': Decimal('1000'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Apr,May,Jun',
        },
        {
            'name': 'Cashew Apple',
            'local_name': 'Kanju',
            'category': fruits,
            'calories': Decimal('43'),
            'protein': Decimal('0.3'),
            'carbohydrates': Decimal('10'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('0.6'),
            'average_price_per_kg': Decimal('200'),
            'is_vegetarian': True,
            'is_vegan': True,
            'is_seasonal': True,
            'available_months': 'Feb,Mar,Apr',
        },
        {
            'name': 'Soursop',
            'local_name': 'Shawashika',
            'category': fruits,
            'calories': Decimal('66'),
            'protein': Decimal('1'),
            'carbohydrates': Decimal('17'),
            'fats': Decimal('0.3'),
            'fiber': Decimal('3.3'),
            'average_price_per_kg': Decimal('600'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Avocado',
            'local_name': 'Piya',
            'category': fruits,
            'calories': Decimal('160'),
            'protein': Decimal('2'),
            'carbohydrates': Decimal('9'),
            'fats': Decimal('15'),
            'fiber': Decimal('7'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
    ]
    
    created = 0
    for fruit in fruit_data:
        _, is_created = Food.objects.get_or_create(name=fruit['name'], defaults=fruit)
        if is_created:
            created += 1
    
    print(f"✓ {created} fruits added")


def seed_oils_and_dairy():
    """Add oils and dairy products"""
    oils = FoodCategory.objects.get(name='Oils & Fats')
    dairy = FoodCategory.objects.get(name='Dairy & Alternatives')
    
    oil_data = [
        {
            'name': 'Palm Oil',
            'local_name': 'Man gyada (Hausa), Epo pupa (Yoruba)',
            'category': oils,
            'calories': Decimal('884'),
            'protein': Decimal('0'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('100'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1500'),
            'is_vegetarian': True,
            'is_vegan': True,
            'vitamin_a': Decimal('30000'),
        },
        {
            'name': 'Groundnut Oil',
            'local_name': 'Mai gyada, Epo epa',
            'category': oils,
            'calories': Decimal('884'),
            'protein': Decimal('0'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('100'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2000'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Vegetable Oil',
            'local_name': 'Mai',
            'category': oils,
            'calories': Decimal('884'),
            'protein': Decimal('0'),
            'carbohydrates': Decimal('0'),
            'fats': Decimal('100'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1800'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
        {
            'name': 'Butter',
            'local_name': 'Bota',
            'category': oils,
            'calories': Decimal('717'),
            'protein': Decimal('0.9'),
            'carbohydrates': Decimal('0.1'),
            'fats': Decimal('81'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('3500'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Margarine',
            'local_name': 'Blue Band',
            'category': oils,
            'calories': Decimal('717'),
            'protein': Decimal('0.2'),
            'carbohydrates': Decimal('0.9'),
            'fats': Decimal('80'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('2500'),
            'is_vegetarian': True,
            'is_vegan': True,
        },
    ]
    
    dairy_data = [
        {
            'name': 'Fresh Milk (Whole)',
            'local_name': 'Madara/Nono',
            'category': dairy,
            'calories': Decimal('61'),
            'protein': Decimal('3.2'),
            'carbohydrates': Decimal('4.8'),
            'fats': Decimal('3.3'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('800'),
            'is_vegetarian': True,
            'is_vegan': False,
            'calcium': Decimal('113'),
        },
        {
            'name': 'Powdered Milk',
            'local_name': 'Peak Milk',
            'category': dairy,
            'calories': Decimal('496'),
            'protein': Decimal('26'),
            'carbohydrates': Decimal('38'),
            'fats': Decimal('27'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('4000'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Evaporated Milk',
            'local_name': 'Tin Milk',
            'category': dairy,
            'calories': Decimal('135'),
            'protein': Decimal('6.8'),
            'carbohydrates': Decimal('10'),
            'fats': Decimal('7.6'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1500'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Yogurt (Plain)',
            'local_name': 'Yoghurt',
            'category': dairy,
            'calories': Decimal('59'),
            'protein': Decimal('3.5'),
            'carbohydrates': Decimal('4.7'),
            'fats': Decimal('3.3'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('1200'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
        {
            'name': 'Cheese (Cheddar)',
            'local_name': 'Cheese',
            'category': dairy,
            'calories': Decimal('403'),
            'protein': Decimal('25'),
            'carbohydrates': Decimal('1.3'),
            'fats': Decimal('33'),
            'fiber': Decimal('0'),
            'average_price_per_kg': Decimal('4500'),
            'is_vegetarian': True,
            'is_vegan': False,
            'calcium': Decimal('721'),
        },
        {
            'name': 'Fura da Nono',
            'local_name': 'Fura da nono',
            'category': dairy,
            'calories': Decimal('120'),
            'protein': Decimal('4'),
            'carbohydrates': Decimal('22'),
            'fats': Decimal('2'),
            'fiber': Decimal('1'),
            'average_price_per_kg': Decimal('500'),
            'is_vegetarian': True,
            'is_vegan': False,
        },
    ]
    
    created = 0
    for item in oil_data + dairy_data:
        _, is_created = Food.objects.get_or_create(name=item['name'], defaults=item)
        if is_created:
            created += 1
    
    print(f"✓ {created} oils and dairy products added")


def run_expanded_seed():
    """Run all expanded seed functions"""
    print("\n🌱 Adding expanded Nigerian food database...\n")
    
    seed_expanded_foods()
    seed_expanded_vegetables()
    seed_fruits()
    seed_oils_and_dairy()
    
    print("\n✅ Expanded database seeding completed!\n")
    print("Summary:")
    print(f"  - Total Foods: {Food.objects.count()}")
    print(f"  - Grains & Starches: {Food.objects.filter(category__name='Grains & Starches').count()}")
    print(f"  - Proteins: {Food.objects.filter(category__name='Proteins').count()}")
    print(f"  - Vegetables: {Food.objects.filter(category__name='Vegetables').count()}")
    print(f"  - Fruits: {Food.objects.filter(category__name='Fruits').count()}")
    print(f"  - Legumes: {Food.objects.filter(category__name='Legumes').count()}")
    print(f"  - Oils & Fats: {Food.objects.filter(category__name='Oils & Fats').count()}")
    print(f"  - Dairy: {Food.objects.filter(category__name='Dairy & Alternatives').count()}")


if __name__ == '__main__':
    run_expanded_seed()