# Generated by Django 4.2.7 on 2025-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mg per 100g', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mg per 100g', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mcg per 100g', max_digits=8, null=True),
        ),
    ]
